config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tweets
  post 'tweets/:id/like', to: 'tweets#like', as: 'tweet_like'
  post 'tweets/:id/retweet', to: 'tweets#retweet', as: 'tweet_retweet'
  root 'tweets#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
      }

  devise_scope :user do
    post '/users/:id/friend', to: 'users/registrations#friend', as: 'user_friend'
  end

  namespace :api do
    get 'news', to: 'api#news'
    get ':start_date/:end_date', to: 'api#inbetween', as: 'inbetween'
    post 'create', to: 'api#create'
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :tweets, class_name: 'Tweet', foreign_key: 'tweet_id', dependent: :destroy
  belongs_to :user
  belongs_to :ref_tweet, class_name: 'Tweet', foreign_key: 'tweet_id', optional: true
  validates :content, presence: true
  paginates_per 50

  def user_pic
    user.profile_pic
  end

  def like(user)
    Like.create(user: user, tweet: self)
  end

  def unlike(user)
    likes.where(user: user).destroy_all
  end

  def liked?(user)
    likes.where(user: user).any?
  end

  def like_toggler(user)
    if liked?(user)
      unlike(user)
    else
      like(user)
    end
  end

  def author
    user.username
  end

  def like_counter
    likes.count
  end

  def retweet(user)
    Tweet.create(ref_tweet: self, content: content, user: user)
  end

  def retweet_counter
    tweets.count
  end

  scope :tweets_for_me, ->(user) { where(user: user.friend_users) if user.present? }
  scope :news, -> { last(50) }
  scope :inbetween, ->(start_date, end_date) { where(created_at: start_date..end_date)}
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  http_basic_authenticate_with name: "hello", password: "world", except: :index
  before_action :set_tweet, only: %i[show edit update destroy like retweet]

  def index
    @q = Tweet.tweets_for_me(current_user).ransack(params[:q])
    @tweets = @q.result.order(created_at: :desc).page(params[:page])
    @tweet = Tweet.new
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
    end
  end

  def like
    @tweet.like_toggler(current_user)

    respond_to do |format|
      if @tweet.liked?(current_user)
        format.html { redirect_to root_path, notice: 'Tweet liked' }
      else
        format.html { redirect_to root_path, notice: 'Tweet unliked' }
      end
    end
  end

  def retweet
    retweet = @tweet.retweet(current_user)
    respond_to do |format|
      if retweet.save
        format.html { redirect_to root_path, notice: 'Retweet Successful!' }
      else
        format.html { redirect_to root_path, notice: 'Retweet Unsuccessful :-(' }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def render_hashtag(content)
    content.gsub(/#\w+/) { |w| link_to w, "tweets?q%5Bcontent_cont%5D=#{w.delete('#')}&commit=Search" }.html_safe
  end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Create_New_Tweet%>
    <%= form.text_area :content, class: 'form-control'  %>
  </div>


  <div class="form-group">
    <%= form. button :Tweet,  class: "btn btn-info btn-sm" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="col mb-3">
  <div class="card <%= local_assigns[:retweet] ? 'card-retweet' : 'card-tweet' %>">
    <div class="card-body">
      <div class="tweet-header">
        <%= link_to image_tag(tweet.user_pic, style: 'width:50px; height:50px', class: 'user-picture'), tweet.user_pic, target: '_blank' %>
        <div class="tweet-header-left">
          <h5 class="card-title tweet-title"><%= tweet.user %></h5> <br>
          <small class="card-subtitle text-muted">
            <%= link_to "#{distance_of_time_in_words(Time.now, tweet.created_at)} ago", tweet_path(tweet) %>
          </small>
        </div>
        <% if user_signed_in? && !local_assigns[:retweet] %>
        <small class="text-muted tweet-unfriend-link">
          <%= link_to(current_user.friends?(tweet.user) ? 'Unfriend' : 'Friend', user_friend_path(tweet.user), method: :post) %>
        </small>
      <% end %>

      </div>
      <p class="card-text"><%= render_hashtag(tweet.content) %></p>
      <% if tweet.ref_tweet %>
      <%= render tweet.ref_tweet, retweet: true %>
      <% end %>
      <% if user_signed_in? %>
      <div class="card-text tweet-buttons">
        <%= link_to tweet_like_path(tweet), method: :post, class:'px-2' do %>
          <% if tweet.liked?(current_user) %>
            <%= fa_icon('heart', type: :solid, class: 'red-icon') %>
          <% else %>
            <%= fa_icon('heart', type: :regular) %> 
          <% end %>
        <% end %>
        <%= tweet.like_counter %> 
        <%= link_to tweet_retweet_path(tweet), method: :post, class:'px-2' do %>
        <%= fa_icon('retweet', type: :solid) %>
        <% end %>
        <%= tweet.retweet_counter %> 
      </div>
      <% else %>
        <div class="card-text tweet-buttons text-muted">
              <%= fa_icon('heart', type: :solid) %><%= tweet.like_counter %>
              <%= fa_icon('retweet', type: :solid) %><%= tweet.retweet_counter %> 
        </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %> 
  <%= render 'form', tweet: @tweet %>
  <br/>
  <h4>People you should be friends with</h4>
  <div class="row row-cols-2 row-cols-lg-4 suggested-friends-top">
    <% current_user.suggested_friends.each do |fr| %>
    <div class="p-2">
      <div class="suggested-friends">
        <%= image_tag(fr.profile_pic, style: 'width:50px; height:50px', class: 'user-picture') %>
        <h5><%= fr %></h5>
        <br>
        <%= link_to(current_user.friends?(fr) ? 'Unfriend' : 'Friend', user_friend_path(fr), method: :post, class: "btn btn-friend btn-sm")  %>
      </div>
    </div>
    <% end %>
  </div>
<% end %>
<div class="my-3 tweets-header-outer">
  <span class="display-4">Tweets</span>
  <%= search_form_for @q, class: "form-inline search-bar" do |f| %>
    <%= f.search_field :content_cont, class: "form-control mr-2" %>
    <%= f.submit class: "btn btn-info btn-sm" %>
  <% end %>
</div>
<% if @tweets.any? %>
  <div class="row row-cols-1 row-cols-xl-2">
    <%= render(@tweets) %>
  </div>
<% else %>
  <h5>No results found</h5>
  <p>Please check your search</p>
<% end %>
<div class="my-3"><%= paginate @tweets %></div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h4 class="display-5 my-3">Tweet</h4>

<%= render @tweet, retweet: false %>

<h4 class="display-7 my-3">Likes</h4>
<ul>
  <% @tweet.likes.each do |like| %>
    <li class="tweet-detail-li">
      <%= image_tag(like.user_pic, style: 'width:50px; height:50px', class: 'user-picture') %>
    </li>
  <% end %>
</ul>
<% if @tweet.user == current_user %>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<% end %>
<%= link_to 'Back', tweets_path %>