config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tweets
  post 'tweets/:id/like', to: 'tweets#like', as: 'tweet_like'
  post 'tweets/:id/retweet', to: 'tweets#retweet', as: 'tweet_retweet'
  root 'tweets#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
      }

  devise_scope :user do
    post '/users/:id/friend', to: 'users/registrations#friend', as: 'user_friend'
  end

  namespace :api do
    get 'news', to: 'api#news'
    get ':start_date/:end_date', to: 'api#inbetween', as: 'inbetween'
    post 'create', to: 'api#create'
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-brand">
      <%= link_to image_tag('twisted.png', style: 'width:20px; height:25px', class: 'd-inline-block align-text-top') , root_path  %> 
      Twisted
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav nav-ra">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= image_tag(current_user.profile_pic, style: 'width:50px; height:50px', class: 'user-picture') %>
        </li>
        <li class="nav-item">
          <%= link_to current_user, edit_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item"><%= link_to 'Log In', new_user_session_path, class:'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %></li>
        <% end %>
        <li class="nav-item"><%= link_to 'Admin', admin_root_path, class:'nav-link', target:'_blank' %></li>
      </ul>
    </div>
  </div>
</nav>